name: Build
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          brew install xcodegen
          xcodegen generate
          pod repo update
          pod install
      - name: xcodebuild
        run: |
          xcodebuild -workspace Synapse.xcworkspace \
                     -scheme Synapse \
                     -configuration Release \
                     -sdk iphoneos \
                     -destination 'generic/platform=iOS' \
                     -derivedDataPath build \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     clean build
      - name: Export
        run: |
          mkdir Payload
          cp -R build/Build/Products/Release-iphoneos/Synapse.app Payload/
          zip -r Synapse.ipa Payload
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Synapse-IPA
          path: Synapse.ipa
